---
- name: Configurar servidor Node.js com MongoDB nas VMs
  hosts: servidores
  become: true

  tasks:
    - name: Atualiza pacotes
      apt:
        update_cache: yes

    - name: Instala pacotes necessários
      apt:
        name:
          - curl
          - git
          - build-essential
        state: present

    - name: Instala Node.js 18
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs

    - name: Instala MongoDB
      shell: |
        wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" > /etc/apt/sources.list.d/mongodb-org-4.4.list
        apt-get update
        apt-get install -y mongodb-org
        systemctl enable mongod
        systemctl start mongod
      args:
        creates: /etc/apt/sources.list.d/mongodb-org-4.4.list

    - name: Clona o repositório da aplicação
      git:
        repo: https://github.com/FagnerTimoteo/Gapi.git
        dest: /home/vagrant/app
        version: feature/ansible

    - name: Instala dependências do Node
      npm:
        path: /home/vagrant/app
        production: no

    - name: Instala nodemon globalmente
      npm:
        name: nodemon
        global: yes

    - name: Instala PM2 globalmente
      npm:
        name: pm2
        global: yes

    - name: Inicia aplicação com PM2
      shell: |
        pm2 start app.js --name gapi
        pm2 save
      args:
        chdir: /home/vagrant/app
